jj/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fee;

import java.awt.print.PrinterException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hp
 */
public class Fee_Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Fee_Receipt
     */
    public Fee_Receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        lblFather = new javax.swing.JLabel();
        lblEnrollment = new javax.swing.JLabel();
        lblProgramme = new javax.swing.JLabel();
        lblMobile = new javax.swing.JLabel();
        lblFeesAmount = new javax.swing.JLabel();
        txtStudent = new javax.swing.JTextField();
        txtFather = new javax.swing.JTextField();
        txtEnrollment = new javax.swing.JTextField();
        txtProgramme = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtFeesAmount = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnPrintReceipt = new javax.swing.JButton();
        btnGenerateReceipt = new javax.swing.JButton();
        spnl = new javax.swing.JScrollPane();
        txtFeeReceipt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblHeading.setBackground(new java.awt.Color(255, 255, 255));
        lblHeading.setFont(new java.awt.Font("Calibri", 2, 48)); // NOI18N
        lblHeading.setText("Fee Receipt System");

        lblStudent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblStudent.setText("Enter Enrollment no. :");

        lblFather.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFather.setText("Enter Father Name   :");

        lblEnrollment.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEnrollment.setText("Enter Programme     :");

        lblProgramme.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblProgramme.setText("Enter Mobile No.       :");

        lblMobile.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblMobile.setText("Enter Fees Amount    :");

        lblFeesAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFeesAmount.setText("Enter Student Name :");

        txtStudent.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtStudent.setText("Deepa");

        txtFather.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtFather.setText("jjjj");

        txtEnrollment.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnrollmentActionPerformed(evt);
            }
        });

        txtProgramme.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtMobile.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtFeesAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtFeesAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFeesAmountActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnPrintReceipt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrintReceipt.setText("Print Receipt");
        btnPrintReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReceiptActionPerformed(evt);
            }
        });

        btnGenerateReceipt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGenerateReceipt.setText("Generate Receipt");
        btnGenerateReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReceiptActionPerformed(evt);
            }
        });

        txtFeeReceipt.setEditable(false);
        txtFeeReceipt.setColumns(20);
        txtFeeReceipt.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtFeeReceipt.setRows(5);
        spnl.setViewportView(txtFeeReceipt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnGenerateReceipt)
                                .addGap(57, 57, 57)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPrintReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMobile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFeesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFeesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFather, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProgramme, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblHeading))
                        .addComponent(lblEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProgramme, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFather, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(391, 391, 391)))
                .addComponent(spnl, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblHeading)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFeesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFather, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFather, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProgramme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProgramme, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFeesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrintReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerateReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(spnl, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtFeeReceipt.setText("");
        txtStudent.setText("");
        txtFather.setText("");
        txtEnrollment.setText("");
        txtProgramme.setText("");
        txtMobile.setText("");
        txtFeesAmount.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnGenerateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReceiptActionPerformed
        // TODO add your handling code here:
        txtFeeReceipt.setText("**************************************\n");
        txtFeeReceipt.setText(txtFeeReceipt.getText()+"*          Fees Receipt              *\n");
        txtFeeReceipt.setText(txtFeeReceipt.getText()+"**************************************\n");

        Date obj = new Date();
        String date = obj.toString();
        txtFeeReceipt.setText(txtFeeReceipt.getText()+"\n\n"+date+"\n\n");
        txtFeeReceipt.setText(txtFeeReceipt.getText()+"Student Name :"+txtStudent.getText()+"\n\n");
        txtFeeReceipt.setText(txtFeeReceipt.getText()+"Father Name"+txtFather.getText()+"\n\n");
        txtFeeReceipt.setText(txtFeeReceipt.getText()+"Enrollment No. :"+txtEnrollment.getText()+"\n\n");
        txtFeeReceipt.setText(txtFeeReceipt.getText()+"Programme :"+txtProgramme.getText()+"\n\n");
        txtFeeReceipt.setText(txtFeeReceipt.getText()+"Mobile No. :"+txtMobile.getText()+"\n\n");
        txtFeeReceipt.setText(txtFeeReceipt.getText()+"Fees Amount :"+txtFeesAmount.getText()+"\n\n");
        txtFeeReceipt.setText(txtFeeReceipt.getText()+"\n                            Signature ");
    }//GEN-LAST:event_btnGenerateReceiptActionPerformed

    private void btnPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceiptActionPerformed
        try {
            // TODO add your handling code here:
            txtFeeReceipt.print();
        } catch (PrinterException ex) {
            
        }
    }//GEN-LAST:event_btnPrintReceiptActionPerformed

    private void txtFeesAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFeesAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFeesAmountActionPerformed

    private void txtEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnrollmentActionPerformed
jj        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnrollmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fee_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fee_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fee_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fee_Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Fee_Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReceipt;
    private javax.swing.JButton btnPrintReceipt;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblEnrollment;
    private javax.swing.JLabel lblFather;
    private javax.swing.JLabel lblFeesAmount;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblMobile;
    private javax.swing.JLabel lblProgramme;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JScrollPane spnl;
    private javax.swing.JTextField txtEnrollment;
    private javax.swing.JTextField txtFather;
    private javax.swing.JTextArea txtFeeReceipt;
    private javax.swing.JTextField txtFeesAmount;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtProgramme;
    private javax.swing.JTextField txtStudent;
    // End of variables declaration//GEN-END:variables
}
